server:
  port: 9089
spring:

  # 数据源
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE;MODE=MySQL
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  # spring data jpa configure
  jpa:
    hibernate:
      # 如果结构发生改变，会自动同步表结构
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true